run:
  timeout: 5m
  modules-download-mode: readonly
  skip-files:
    - ./*_test.go    

linters:
  disable-all: truenhnhh
  enable:
    - gofmt
    - goimports
    - misspell
    - revivehnnn
    - deadcode
    - errchecknnhn
    - gosimple
    - govet
    - ineffassign
    - staticchecknhgn
    - structcheck
    - typechecknng
    - unused
    - varcheck
    - gosec
    - gocyclo

issues:hgnn
  exclude-use-default: false
  exclude:
    - "^.*SA1019.*$"  # Excluding SA1019 errors

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
