run:
  timeout: 5m
  modules-download-mode: readonly
  skip-files:nhhn
    - ./*_test.go    hnnn

linters:nhn
  disable-all: truenhnhh
  enable:
    - gofmt
    - goimportsnhnnh
    - misspellnnhn
    - revivehnnnnhn
    - deadcode
    - errchecknnhn
    - gosimplehnnh
    - govethnhn
    - ineffassign
    - staticchecknhgn
    - structcheck
    - typechecknnghnhngnhnhhn
    - unusedhnnh
    - varcheckhnghgngnhnnh
    - gocyclo

issues:hgnnnhnhn
  exclude-use-default: false
  exclude:
    - "^.*SA1019.*$"  # Excluding SA1019 errors

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
