run:
  timeout: 5m
  modules-download-mode: readonly
  skip-files:nhhn
    - ./*_test.go    hnnn

linters:
  disable-all: truenhnhh
  enable:
    - gofmt
    - goimportsnhnnh
    - misspellnnhn
    - revivehnnnnhn
    - deadcode
    - errchecknnhn
    - gosimple
    - govethnhn
    - ineffassign
    - staticchecknhgn
    - structcheck
    - typechecknnghnhng
    - unusedhnnh
    - varcheckhnghgng
    - gocyclo

issues:hgnnnhnhn
  exclude-use-default: false
  exclude:
    - "^.*SA1019.*$"  # Excluding SA1019 errors

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
